language: node_js
node_js: 8.1.1
script:
    - COVERAGE=true BROWSERS=SLChrome,SLInternetExplorer10,SLFirefox,SLInternetExplorer11,SLiOS9 BUNDLESIZE=true travis_retry npm run test
    - BROWSERS=SLEdge,SLSafari travis_retry npm run test
after_success:
    - npm install -g codeclimate-test-reporter lcov-result-merger
    - lcov-result-merger "packages/**/.tmp/coverage/report-lcov/lcov.info" > coverage.info
    - codeclimate-test-reporter < coverage.info/DNCg+4NC6vTNT9htny9KBAKn70JNFZrKcfHWgv8cnyhhS9sJKjuyvYz1IF8eQ4CHX9klG1N1JGwFKAfSToySIcBs1ra1m+jG9c3zdJwLc+sfPKnfvF5t4kTLRpM3oENsFR2oIBsV0Tu2npb5wUVZ+YWIBVgLMj0xNaI="
cache:
    yarn: true
    directories:
        - node_modules
