name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
        - '12.x'
        - '14.x'
        - '16.x'
        - '17.x'

    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2.4.1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: yarn install
    - name: Run ESLint
      run: yarn eslint
