name: Release

on:
  release:
    types: [published]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    name: GPR
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3.2.0
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/
        scope: '@jonhue'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GPR_AUTH_TOKEN }}

  publish-npm:
    runs-on: ubuntu-latest
    name: NPM
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3.2.0
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
